### ISSUE TITLE
Feature request: Add deploy to Heroku button to Readme

### ISSUE THREAD

**Issue by chrisgagne** [etsy/opsweekly#27]
It seems like it would be nice for README.md to have a "Deploy to Heroku" button, like this project over here: https://github.com/stripe/pagerbot. We'd (PagerDuty) be happy to add a small bounty on BountySource if anyone else would like to see this added. :)

**Comment by chrisgagne** [comment]
@dalexj I believe there is a $100 bounty waiting for you... :)

**Comment by dalexj** [comment]
oh yeah. thanks!
